### PR TITLE
Add general advise article and section

### PR DESCRIPTION
**Pull request by Createdd**

### CODE REVIEW

**Comment by cedmax** [comment]
Hi @Createdd, 
I find you article really interesting, thanks for submitting it, I'm just not sure about the new section.
It feels more the retrospective of a specific meetup, rather than general advise (even if I appreciate there are some takeaways anyone could benefit from, reason why I think it's an absolutely valid submission). 

I was wondering what you'd think about calling the new section something on the lines of "case studies" or such?

I'm open to ideas, but I'd rather not propose it as general advise when the angle is substantially different, if it makes sense.

Cheers
Marco

**Comment by Createdd** [comment]
@cedmax  yeah of course, no worries :) 
Just thought it might be interesting for some ;) 
Stay motivated, 
Daniel

**Comment by cedmax** [comment]
It's definitely interesting, let's just find a category name that suits it better! 
if you have anything better than "case studies" (which arguibly is not the best), I'd love to hear it :)

**Comment by Createdd** [comment]
@cedmax  I have opened a new PR :) https://github.com/fromthefront/awesome-how-to-run-events/pull/10

**Pull request closed without merging**
