### PR TITLE
Added how to run a meetup

### PR DESCRIPTION
**Pull request by nikgraf**
It includes long-term tips, but also best practices for the events.

### CODE REVIEW

**Comment by cedmax** [comment]
Hi @nikgraf, 
thanks for your submission, I was wondering if instead of adding a new category you could change the "Setting up a conference" to "Setting up an event" (please keep in mind the link in the content table too) and add your link to that section. 

Thanks
Marco

**Comment by nikgraf** [comment]
@cedmax sounds good, just updated the PR

**Comment by cedmax** [comment]
Cool, I fixed the title case (I hope you don't mind) and merged. 
Thanks for contributing :)

**Comment by nikgraf** [comment]
great, thanks 👏

**Pull request merged**
